#if UNITY_EDITOR
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace Editor
{
    public static class EnumGenerator
    {
        private const string CreatePath = "Assets/Scripts/Generated";
        private const string NamePostfix = "Group";
        
        public static void Generate(
            string[] names,
            string enumName,
            string namespaceName = "Generated")
        {
            if (names == null || names.Length == 0)
            {
                EditorUtility.DisplayDialog("Error", "No names provided for enum generation.", "OK");
                return;
            }

            enumName += NamePostfix;
            
            string fullPath = Path.GetFullPath(CreatePath + "/" + enumName + ".cs");
            string directory = Path.GetDirectoryName(fullPath);

            if (Directory.Exists(directory) == false)
            {
                Directory.CreateDirectory(directory);
            }

            if (File.Exists(fullPath))
            {
                File.Delete(fullPath);
            }

            string[] enumEntries = names
                .Select(SanitizeEnumName)
                .Select(name => $"    {name}")
                .ToArray();

            string enumContent = GetFileText(namespaceName, enumName, enumEntries);

            File.WriteAllText(fullPath, enumContent);
            AssetDatabase.Refresh();

            Debug.Log($"{enumName} enum generated at: {fullPath}");
            EditorUtility.RevealInFinder(directory);
        }

        private static string SanitizeEnumName(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                return "InvalidName";
            }

            string sanitized = name
                .Replace(' ', '_')
                .Replace('-', '_')
                .Replace('.', '_');

            if (!string.IsNullOrEmpty(sanitized) && char.IsDigit(sanitized[0]))
            {
                sanitized = "_" + sanitized;
            }

            sanitized = Regex.Replace(sanitized, @"[^a-zA-Z0-9_]", "");

            return string.IsNullOrEmpty(sanitized) ? "InvalidName" : sanitized;
        }

        private static string GetFileText(string namespaceName, string enumName, string[] enumEntries)
        {
            return $@"// Auto-generated by HekapooGenerator
// Do not modify manually

namespace {namespaceName}
{{
    public enum {enumName}
    {{
    {string.Join(",\n \t", enumEntries)}
    }}
}}
";
        }
    }
}
#endif